# Generated by Django 5.2.4 on 2025-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('competition', 'Competition'), ('award', 'Award'), ('publication', 'Publication'), ('volunteer', 'Volunteer Work'), ('leadership', 'Leadership'), ('other', 'Other')], default='other', max_length=20)),
                ('organization', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('result', models.CharField(blank=True, help_text='e.g., 1st Place, Finalist, etc.', max_length=100, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('technologies_used', models.TextField(blank=True, help_text='Comma-separated list of technologies used', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['display_order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('certification_type', models.CharField(choices=[('technical', 'Technical Certification'), ('professional', 'Professional Certification'), ('university', 'University Course'), ('online', 'Online Course')], default='technical', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills_covered', models.TextField(blank=True, help_text='Comma-separated list of skills covered', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['display_order', '-issue_date'],
            },
        ),
    ]
