# Generated by Django 5.2.4 on 2025-11-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_achievement_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('certificate', 'Certificate'), ('online', 'Online Course')], default='bachelor', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, help_text='e.g., GPA, Percentage, Grade', max_length=50, null=True)),
                ('courses', models.TextField(blank=True, help_text='Comma-separated list of key courses', null=True)),
                ('achievements', models.TextField(blank=True, help_text='Comma-separated list of achievements', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='education/logos/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='education/certificates/')),
                ('display_order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-start_date'],
            },
        ),
    ]
