# Generated by Django 5.2.8 on 2026-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_type',
            field=models.CharField(choices=[('foundational', 'Foundational Certification'), ('associate', 'Associate Certification'), ('technical', 'Technical Certification'), ('professional', 'Professional Certification'), ('university', 'University Course'), ('online', 'Online Course'), ('course_completion', 'Course Completion')], default='technical', max_length=20),
        ),
    ]
